project_id = "jazjzwhbagwllensnkaz"

[functions.send-message-notification]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.change-subscription-plan]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.cleanup-expired-properties]
verify_jwt = false

[functions.send-moderation-notification]
verify_jwt = false

[functions.send-expiry-reminders]
verify_jwt = false

[functions.get-user-by-email]
verify_jwt = true
